version: '3'

services:
  viewtube-db-dev:
    container_name: viewtube-db-dev
    image: mongo
    networks:
      - viewtube-local
    ports:
      - 27017:27017

  viewtube-redis-dev:
    container_name: viewtube-redis-dev
    image: redis
    networks:
      - viewtube-local
    ports:
      - 6379:6379

networks:
  viewtube-local:
    driver: bridge
