name: Daily Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test-job:
    name: Daily Tests
    timeout-minutes: 60
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Node.js PR workflow step ${{ matrix.command }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Get current date and time
        id: date-time
        run: echo "::set-output name=date-time::$(date +'%Y-%m-%d %H:%M:%S')"

      - run: yarn install

      - name: Run tests
        id: run_tests
        run: |
          echo "::set-output name=test-result::$(yarn test | tail)"

      - name: Send test status notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            â˜€ï¸ Daily test run ${{ steps.date-time.outputs.date-time }}

            ğŸ§ª Test result: ${{ steps.run_tests.outcome == 'success' ? 'âœ…' : 'âŒ' }} ${{ steps.run_tests.outputs.test-result }}

            [ğŸ”— Link to test](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

# ğŸ“ Detailed information:
# ```
# ${{ steps.run_tests.outputs.test-result }}
# ```
