name: Daily Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test-job:
    name: Daily Tests
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js PR workflow step ${{ matrix.command }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get current date and time
        id: date-time
        run: echo "date-time=$(TZ='Europe/Zurich' date +'%Y-%m-%d %H:%M:%S %Z') >> $GITHUB_OUTPUT"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        id: run_tests
        run: |
          echo "test-result=$(pnpm test | tail)" >> $GITHUB_OUTPUT

      - name: Send test status notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            â˜€ï¸ Daily test run ${{ steps.date-time.outputs.date-time }}

            ğŸ§ª Test result: ${{ steps.run_tests.outcome != 'success' && 'âŒ' || 'âœ…' }} ${{ steps.run_tests.outcome }}

            [ğŸ”— Link to test](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

# ğŸ“ Detailed information:
# ```
# ${{ steps.run_tests.outputs.test-result }}
# ```
